apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep1
  name: dep1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: dep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep1
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
        - tail
        - -f
        - /dev/null
        resources: {}
status: {}