name: ci

on: push

env:
  K3S_VERSION: v1.24.6+k3s1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Prepare k3s offline package
      run: |
        bash airgap_installer/download_package.sh ${{ env.K3S_VERSION }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.K3S_VERSION }}"
        title: "${{ env.K3S_VERSION }}"
        prerelease: false
        files: |
          k3s_offline_*.tar.gz

  test_download:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
    - name: Download from github release
      run: |
        ls -lah
        wget -q https://github.com/ren15/k3s_deployment/releases/download/${{ env.K3S_VERSION }}/k3s_offline_${{ env.K3S_VERSION }}.tar.gz
        tar xvf k3s_offline_${{ env.K3S_VERSION }}.tar.gz
        ls -lah k3s*
        k3s_offline/k3s --version
